// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "5a96da87-d308-4e62-93f1-7ffd3ecef004";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onMoistureValueChange();
void onMannualModeChange();
void onWaterPumpChange();

int moisture_Value;
bool mannual_Mode;
bool water_Pump;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(moisture_Value, READWRITE, ON_CHANGE, onMoistureValueChange);
  ArduinoCloud.addProperty(mannual_Mode, READWRITE, ON_CHANGE, onMannualModeChange);
  ArduinoCloud.addProperty(water_Pump, READWRITE, ON_CHANGE, onWaterPumpChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
